project_id = "ktnwehlysguwtjyshqtc"

[functions.meta-lead-webhook]
verify_jwt = false

[functions.public-lead]
verify_jwt = false

[functions.whatsapp-suggest]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-template]
verify_jwt = true
