// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-procedures.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function anonSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-procedures.ts
var list_procedures_default = defineTool({
  name: "list_procedures",
  title: "List procedures",
  description: "List aesthetic procedures offered by the clinic (name, category, default price, description).",
  inputSchema: {
    includeArchived: z.boolean().optional().describe("Include archived procedures. Defaults to false."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows. Default 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeArchived, limit }) => {
    const sb = anonSupabase();
    let q = sb.from("procedures").select("id,name,category,default_price,description,duration,sessions_recommended,archived").order("name", { ascending: true }).limit(limit ?? 100);
    if (!includeArchived) q = q.eq("archived", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { procedures: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-appointments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_upcoming_appointments_default = defineTool2({
  name: "list_upcoming_appointments",
  title: "List upcoming appointments",
  description: "List scheduled appointments starting from now, ordered by date. Returns patient name, procedure, scheduled time, status and value.",
  inputSchema: {
    days: z2.number().int().min(1).max(90).optional().describe("Look-ahead window in days. Default 14."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }) => {
    const sb = anonSupabase();
    const now = /* @__PURE__ */ new Date();
    const until = new Date(now.getTime() + (days ?? 14) * 864e5);
    const { data, error } = await sb.from("appointments").select("id,patient_name,procedure_name,scheduled_at,status,confirmation_status,value").gte("scheduled_at", now.toISOString()).lte("scheduled_at", until.toISOString()).order("scheduled_at", { ascending: true }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_leads_default = defineTool3({
  name: "list_leads",
  title: "List leads",
  description: "List leads in the clinic CRM, optionally filtered by temperature (hot/warm/cold) or stage.",
  inputSchema: {
    temperature: z3.enum(["hot", "warm", "cold"]).optional(),
    stage: z3.enum(["novo", "contato", "qualificado", "agendamento", "convertido", "perdido"]).optional(),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ temperature, stage, limit }) => {
    const sb = anonSupabase();
    let q = sb.from("leads").select(
      "id,name,phone,email,source,campaign,procedure_interest,temperature,stage,score,estimated_value,last_contact_at,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (temperature) q = q.eq("temperature", temperature);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_lead_default = defineTool4({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead in the clinic CRM. Use for capturing prospects from external channels (ads, referrals, chat).",
  inputSchema: {
    name: z4.string().min(1).describe("Lead full name."),
    phone: z4.string().optional().describe("Phone number in E.164 or local format."),
    email: z4.string().email().optional(),
    source: z4.string().optional().describe("Channel origin (e.g. Meta Ads, Google, Indica\xE7\xE3o)."),
    procedureInterest: z4.string().optional().describe("Procedure the lead is interested in."),
    temperature: z4.enum(["hot", "warm", "cold"]).optional(),
    notes: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input) => {
    const sb = anonSupabase();
    const { data, error } = await sb.from("leads").insert({
      name: input.name,
      phone: input.phone ?? null,
      email: input.email ?? null,
      source: input.source ?? "MCP",
      procedure_interest: input.procedureInterest ?? null,
      temperature: input.temperature ?? "warm",
      stage: "novo",
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lead criado: ${data?.id}` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gm-estetica-mcp",
  title: "GM Est\xE9tica Avan\xE7ada",
  version: "0.1.0",
  instructions: "Ferramentas da cl\xEDnica GM Est\xE9tica Avan\xE7ada: consulta de procedimentos, agenda de atendimentos, CRM de leads e cria\xE7\xE3o de novos leads. Use list_procedures para cat\xE1logo, list_upcoming_appointments para agenda futura, list_leads para o funil e create_lead para registrar novos contatos.",
  tools: [list_procedures_default, list_upcoming_appointments_default, list_leads_default, create_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
